# Generated by Django 5.1.2 on 2024-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatepost',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
