# Generated by Django 4.2.16 on 2024-11-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "roommates",
            "0003_alter_amenity_id_alter_comment_id_alter_favorite_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="roommatepost",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=6
            ),
        ),
    ]
