# Generated by Django 4.2.16 on 2024-12-12 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_pendingemailchange"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingemailchange",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
