# Generated by Django 5.1.1 on 2024-10-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="rental_images/"
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "apartment_type",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("1_bed", "1 Bed"),
                            ("2_bed", "2 Bed"),
                            ("3_bed", "3 Bed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sqft", models.IntegerField()),
                ("amenities", models.TextField()),
            ],
        ),
    ]
