# Generated by Django 5.1.1 on 2024-10-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="apartment_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
