# Generated by Django 2.2 on 2024-11-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentpost',
            name='post_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('ROOM', 'Room')], default='APARTMENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='apartmentpost',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
