# Generated by Django 2.2 on 2024-11-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20241105_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
