# Generated by Django 4.2.16 on 2024-11-24 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_alter_amenity_id_alter_apartmentimage_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentpost",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of the apartment must be zero or higher.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
