# Generated by Django 4.2.16 on 2024-11-24 22:06

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_alter_amenity_id_alter_apartmentimage_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentimage",
            name="image",
            field=models.ImageField(
                storage=storages.backends.s3.S3Storage(), upload_to=""
            ),
        ),
    ]
