# Generated by Django 4.2.16 on 2024-11-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0004_alter_apartmentimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentpost",
            name="borough",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
