# Generated by Django 5.1.2 on 2024-11-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20241104_1801'),
        ('rentals', '0004_alter_comment_user'),
    ]

    operations = [
    ]
