# Generated by Django 4.2.16 on 2024-12-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "property_type",
                    models.CharField(
                        choices=[("APARTMENT", "Apartment"), ("ROOM", "Room")],
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
