# Generated by Django 4.2.16 on 2024-12-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricealert",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
